In [1]:
# Dependencies
import pandas as pd
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [2]:
# Load data into dataframes
df = pd.read_csv('resources/train.csv', index_col=0)
df.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
Id,,,,,,,,,,,,,,,,,,,,,
1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [3]:
df['LotFrontage'].fillna(value=0, inplace=True)
df['MasVnrArea'].fillna(value=0, inplace=True)

df.drop(columns='GarageYrBlt', inplace=True)

In [4]:
# Insert dummy variables for categorical data
df_num = pd.get_dummies(df)

In [5]:
# Split train and testing data and separate X, y
train_df, test_df = train_test_split(df_num, random_state=42)

X_train = train_df.drop(columns='SalePrice')
X_test = test_df.drop(columns='SalePrice')

y_train = train_df['SalePrice'].values
y_test = test_df['SalePrice'].values

In [6]:
# Scale data
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [7]:
# fit linear regression model
model = Ridge(alpha=20)
model.fit(X_train_scaled, y_train)

Ridge(alpha=20)

In [8]:
model.score(X_train_scaled, y_train)

0.9355823690264344

In [9]:
model.score(X_test_scaled, y_test)

0.8986651721073147

In [10]:
predicted = model.predict(X_test_scaled)

In [11]:
pct_diff = []
for i in range(len(predicted)):
    p = predicted[i]
    a = y_test[i]
    
    pct_diff.append(round((p - a)/a * 100))

In [12]:
pd.DataFrame({'predicted': predicted, 'actual': y_test, 'pct_diff': pct_diff}).head(50)

        predicted  actual  pct_diff
0   158004.920094  154500       2.0
1   349711.527694  325000       8.0
2    83647.727158  115000     -27.0
3   182029.517831  159000      14.0
4   322763.700252  315500       2.0
5    67916.845469   75500     -10.0
6   235644.679645  311500     -24.0
7   146776.289348  146000       1.0
8    59080.170064   84500     -30.0
9   150485.460598  135500      11.0
10  143563.805577  145000      -1.0
11  103683.045566  130000     -20.0
12   83436.356680   81000       3.0
13  219196.427661  214000       2.0
14  172200.143398  181000      -5.0
15  130992.928923  134500      -3.0
16  185940.349795  183500       1.0
17  123608.784994  135000      -8.0
18  127552.862179  118400       8.0
19  215837.539942  226000      -4.0
20  149911.616804  155000      -3.0
21  204530.522956  210000      -3.0
22  174093.691985  173500       0.0
23  125906.081162  129000      -2.0
24  201159.007659  192000       5.0
25  139474.071486  153900      -9.0
26  195778.838539  181134       8.0
27  104434.332213  141000     -26.0
28  175675.931809  181000      -3.0
29  209711.234404  208900       0.0
30  154541.119950  127000      22.0
31  276996.130712  284000      -2.0
32  235201.237088  200500      17.0
33  106906.620381  135750     -21.0
34  241400.618681  255000      -5.0
35  149637.052454  140000       7.0
36  128274.608708  138000      -7.0
37  201754.856702  219500      -8.0
38  309626.290765  310000      -0.0
39  114409.569749   97000      18.0
40  119356.506250  114500       4.0
41  221955.340370  205000       8.0
42  102575.481428  119500     -14.0
43  369588.482332  253293      46.0
44  132824.676725  128500       3.0
45  140963.107550  117500      20.0
46   97409.789410  115000     -15.0
47  140980.446309  127000      11.0
48  428841.014726  451950      -5.0
49  134142.246294  144000      -7.0

In [13]:
# Match model coefficients with features
coef_df = pd.DataFrame({'Feature': X_train.columns.values, 
                        'Coef': model.coef_.round(),
                        'Coef_Abs': abs(model.coef_.round())})
coef_df

                   Feature    Coef  Coef_Abs
0               MSSubClass -1439.0    1439.0
1              LotFrontage   346.0     346.0
2                  LotArea  6516.0    6516.0
3              OverallQual  9361.0    9361.0
4              OverallCond  5641.0    5641.0
..                     ...     ...       ...
282  SaleCondition_AdjLand    55.0      55.0
283   SaleCondition_Alloca  1425.0    1425.0
284   SaleCondition_Family  -776.0     776.0
285   SaleCondition_Normal  -164.0     164.0
286  SaleCondition_Partial  1560.0    1560.0

[287 rows x 3 columns]

In [14]:
# Sort by largest coefficients
coef_df.sort_values(by=['Coef_Abs'], ascending=False).head(50)

                  Feature     Coef  Coef_Abs
123      RoofMatl_ClyTile -17206.0   17206.0
15              GrLivArea  12511.0   12511.0
13               2ndFlrSF  10555.0   10555.0
3             OverallQual   9361.0    9361.0
11            TotalBsmtSF   8717.0    8717.0
100       Condition2_PosN  -8144.0    8144.0
5               YearBuilt   7812.0    7812.0
8              BsmtFinSF1   7525.0    7525.0
248         GarageQual_Ex   7429.0    7429.0
2                 LotArea   6516.0    6516.0
84   Neighborhood_StoneBr   6077.0    6077.0
253         GarageCond_Ex  -6030.0    6030.0
25             GarageArea   5693.0    5693.0
4             OverallCond   5641.0    5641.0
31               PoolArea   5588.0    5588.0
78   Neighborhood_NridgHt   5388.0    5388.0
12               1stFlrSF   5236.0    5236.0
77   Neighborhood_NoRidge   5233.0    5233.0
181           BsmtQual_Ex   5071.0    5071.0
223        KitchenQual_Ex   4885.0    4885.0
22           TotRmsAbvGrd   4035.0    4035.0
7              MasVnrArea   3802.0    3802.0
190       BsmtExposure_Gd   3728.0    3728.0
23             Fireplaces   3520.0    3520.0
134   Exterior1st_BrkFace   3488.0    3488.0
21           KitchenAbvGr  -3417.0    3417.0
104         BldgType_1Fam   3371.0    3371.0
74     Neighborhood_NAmes  -3206.0    3206.0
166          ExterQual_Ex   3171.0    3171.0
68   Neighborhood_Crawfor   3112.0    3112.0
61          LandSlope_Sev  -3035.0    3035.0
69   Neighborhood_Edwards  -2954.0    2954.0
108       BldgType_TwnhsE  -2920.0    2920.0
192       BsmtExposure_No  -2726.0    2726.0
122        RoofStyle_Shed   2625.0    2625.0
18               FullBath   2550.0    2550.0
55      LotConfig_CulDSac   2548.0    2548.0
107        BldgType_Twnhs  -2432.0    2432.0
79   Neighborhood_OldTown  -2400.0    2400.0
261             PoolQC_Ex   2382.0    2382.0
183           BsmtQual_Gd  -2363.0    2363.0
87      Condition1_Artery  -2354.0    2354.0
73   Neighborhood_Mitchel  -2322.0    2322.0
262             PoolQC_Fa  -2299.0    2299.0
26             WoodDeckSF   2259.0    2259.0
6            YearRemodAdd   2199.0    2199.0
76    Neighborhood_NWAmes  -2194.0    2194.0
98        Condition2_Norm   2188.0    2188.0
92        Condition1_RRAe  -2153.0    2153.0
263             PoolQC_Gd  -2129.0    2129.0

In [15]:
# tune alpha
alpha = [1, 5, 10, 20, 50, 100, 1000, 10000]

for a in alpha:
    model = Ridge(alpha=a)
    model.fit(X_train_scaled, y_train)
    
    print(f'alpha: {a}')
    print(f'model score: {model.score(X_test_scaled, y_test)}')
    print('---------------------------------------')

alpha: 1
model score: 0.8925199599683801
---------------------------------------
alpha: 5
model score: 0.8971931607876975
---------------------------------------
alpha: 10
model score: 0.897990554442712
---------------------------------------
alpha: 20
model score: 0.8986651721073147
---------------------------------------
alpha: 50
model score: 0.8984116890185245
---------------------------------------
alpha: 100
model score: 0.89622214040623
---------------------------------------
alpha: 1000
model score: 0.86653235783008
---------------------------------------
alpha: 10000
model score: 0.6703865716342648
---------------------------------------

## Simplified Model

In [16]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageFinish',
       'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive',
       'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [17]:
# columns to keep
cols = ['GrLivArea', 'Neighborhood', 'OverallQual', 'OverallCond', 'YearBuilt', 'ExterQual', 'TotalBsmtSF', 
       'BsmtFinSF1', 'LotArea', 'TotRmsAbvGrd', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenQual', 
        'BldgType', 'HouseStyle', 'GarageCars', 'SalePrice']

In [18]:
df_simple = df[cols]
df_simple.head()

,GrLivArea,Neighborhood,OverallQual,OverallCond,YearBuilt,ExterQual,TotalBsmtSF,BsmtFinSF1,LotArea,TotRmsAbvGrd,FullBath,HalfBath,BedroomAbvGr,KitchenQual,BldgType,HouseStyle,GarageCars,SalePrice
Id,,,,,,,,,,,,,,,,,,
1,1710,CollgCr,7,5,2003,Gd,856,706,8450,8,2,1,3,Gd,1Fam,2Story,2,208500
2,1262,Veenker,6,8,1976,TA,1262,978,9600,6,2,0,3,TA,1Fam,1Story,2,181500
3,1786,CollgCr,7,5,2001,Gd,920,486,11250,6,2,1,3,Gd,1Fam,2Story,2,223500
4,1717,Crawfor,7,5,1915,TA,756,216,9550,7,1,0,3,Gd,1Fam,2Story,3,140000
5,2198,NoRidge,8,5,2000,Gd,1145,655,14260,9,2,1,4,Gd,1Fam,2Story,3,250000

In [19]:
# Change quality categorical data to numerical (eg. 0-5)
qual = {'Po': 1, 'Fa': 2, 'TA': 3, 'Gd': 4, 'Ex': 5}

df_simple['ExterQual'] = [qual[x] if x is not np.nan else 1 for x in df_simple['ExterQual']]
df_simple['KitchenQual'] = [qual[x] if x is not np.nan else 1 for x in df_simple['KitchenQual']]

C:\Users\esalg\anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\esalg\anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [20]:
# Combine full bath and half bath
df_simple['Bath'] = df_simple['FullBath'] + df_simple['HalfBath'] * 0.5

df_simple.drop(columns=['FullBath', 'HalfBath'], inplace=True)

df_simple

C:\Users\esalg\anaconda3\envs\pythondata\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\esalg\anaconda3\envs\pythondata\lib\site-packages\pandas\core\frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

,GrLivArea,Neighborhood,OverallQual,OverallCond,YearBuilt,ExterQual,TotalBsmtSF,BsmtFinSF1,LotArea,TotRmsAbvGrd,BedroomAbvGr,KitchenQual,BldgType,HouseStyle,GarageCars,SalePrice,Bath
Id,,,,,,,,,,,,,,,,,
1,1710,CollgCr,7,5,2003,4,856,706,8450,8,3,4,1Fam,2Story,2,208500,2.5
2,1262,Veenker,6,8,1976,3,1262,978,9600,6,3,3,1Fam,1Story,2,181500,2.0
3,1786,CollgCr,7,5,2001,4,920,486,11250,6,3,4,1Fam,2Story,2,223500,2.5
4,1717,Crawfor,7,5,1915,3,756,216,9550,7,3,4,1Fam,2Story,3,140000,1.0
5,2198,NoRidge,8,5,2000,4,1145,655,14260,9,4,4,1Fam,2Story,3,250000,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1456,1647,Gilbert,6,5,1999,3,953,0,7917,7,3,3,1Fam,2Story,2,175000,2.5
1457,2073,NWAmes,6,6,1978,3,1542,790,13175,7,3,3,1Fam,1Story,2,210000,2.0
1458,2340,Crawfor,7,9,1941,5,1152,275,9042,9,4,4,1Fam,2Story,1,266500,2.0
1459,1078,NAmes,5,6,1950,3,1078,49,9717,5,2,4,1Fam,1Story,1,142125,1.0
1460,1256,Edwards,5,6,1965,4,1256,830,9937,6,3,3,1Fam,1Story,1,147500,1.5

In [21]:
# Insert dummy variables for categorical data
df_simple_num = pd.get_dummies(df_simple)

# Split train and testing data and separate X, y
train_df, test_df = train_test_split(df_simple_num, random_state=42)

X_train = train_df.drop(columns='SalePrice')
X_test = test_df.drop(columns='SalePrice')

y_train = train_df['SalePrice'].values
y_test = test_df['SalePrice'].values

In [22]:
# Scale data
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
# fit linear regression model
model = Ridge(alpha=1)
model.fit(X_train_scaled, y_train)

Ridge(alpha=1)

In [24]:
model.score(X_train_scaled, y_train)

0.8411858205687788

In [25]:
model.score(X_test_scaled, y_test)

0.864767217574047

In [26]:
predicted = model.predict(X_test_scaled)

pct_diff = []
for i in range(len(predicted)):
    p = predicted[i]
    a = y_test[i]
    
    pct_diff.append(round((p - a)/a * 100))

pd.DataFrame({'predicted': predicted, 'actual': y_test, 'pct_diff': pct_diff}).head(50)

        predicted  actual  pct_diff
0   147950.026535  154500      -4.0
1   331210.136027  325000       2.0
2   110928.002216  115000      -4.0
3   181445.778118  159000      14.0
4   287775.770297  315500      -9.0
5    71874.879156   75500      -5.0
6   251532.971742  311500     -19.0
7   132255.738264  146000      -9.0
8    57572.970013   84500     -32.0
9   131655.632758  135500      -3.0
10  148419.825974  145000       2.0
11  117847.055682  130000      -9.0
12   92700.363115   81000      14.0
13  266731.939704  214000      25.0
14  171356.592418  181000      -5.0
15  140256.916718  134500       4.0
16  202067.963558  183500      10.0
17  137969.953525  135000       2.0
18  117479.835531  118400      -1.0
19  226119.817393  226000       0.0
20  166815.851761  155000       8.0
21  232014.141088  210000      10.0
22  186189.697051  173500       7.0
23  114937.762195  129000     -11.0
24  211235.476548  192000      10.0
25  142583.774477  153900      -7.0
26  197359.591022  181134       9.0
27  102864.083993  141000     -27.0
28  167550.443375  181000      -7.0
29  186529.841327  208900     -11.0
30  123846.597428  127000      -2.0
31  302522.041232  284000       7.0
32  264484.156886  200500      32.0
33  104095.601096  135750     -23.0
34  266179.149877  255000       4.0
35  144719.955829  140000       3.0
36  138997.989698  138000       1.0
37  213773.038602  219500      -3.0
38  339069.976849  310000       9.0
39  101846.858719   97000       5.0
40  134175.943443  114500      17.0
41  229436.711644  205000      12.0
42  114311.167787  119500      -4.0
43  334967.694682  253293      32.0
44  127200.525284  128500      -1.0
45  117802.977300  117500       0.0
46  112792.762671  115000      -2.0
47  128400.515780  127000       1.0
48  381327.981455  451950     -16.0
49  135957.259748  144000      -6.0

In [27]:
# Match model coefficients with features
coef_df = pd.DataFrame({'Feature': X_train.columns.values, 
                        'Coef': model.coef_.round(),
                        'Coef_Abs': abs(model.coef_.round())})

# Sort by largest coefficients
coef_df.sort_values(by=['Coef_Abs'], ascending=False)

                 Feature     Coef  Coef_Abs
0              GrLivArea  24725.0   24725.0
1            OverallQual  16937.0   16937.0
29  Neighborhood_NridgHt  10753.0   10753.0
3              YearBuilt  10421.0   10421.0
35  Neighborhood_StoneBr   7683.0    7683.0
28  Neighborhood_NoRidge   7409.0    7409.0
6             BsmtFinSF1   7338.0    7338.0
11            GarageCars   6930.0    6930.0
38         BldgType_1Fam   5998.0    5998.0
10           KitchenQual   5864.0    5864.0
41        BldgType_Twnhs  -5481.0    5481.0
8           TotRmsAbvGrd   5420.0    5420.0
42       BldgType_TwnhsE  -5063.0    5063.0
7                LotArea   5012.0    5012.0
2            OverallCond   5004.0    5004.0
48     HouseStyle_2Story  -4801.0    4801.0
45     HouseStyle_1Story   4779.0    4779.0
12                  Bath   4331.0    4331.0
20  Neighborhood_Edwards  -4178.0    4178.0
30  Neighborhood_OldTown  -4050.0    4050.0
9           BedroomAbvGr  -4036.0    4036.0
25    Neighborhood_NAmes  -3991.0    3991.0
4              ExterQual   3644.0    3644.0
19  Neighborhood_Crawfor   3628.0    3628.0
27   Neighborhood_NWAmes  -3606.0    3606.0
34  Neighborhood_Somerst   3406.0    3406.0
37  Neighborhood_Veenker   2847.0    2847.0
32   Neighborhood_Sawyer  -2664.0    2664.0
21  Neighborhood_Gilbert  -2323.0    2323.0
33  Neighborhood_SawyerW  -2290.0    2290.0
18  Neighborhood_CollgCr  -1906.0    1906.0
15   Neighborhood_BrDale   1877.0    1877.0
47     HouseStyle_2.5Unf  -1750.0    1750.0
24  Neighborhood_Mitchel  -1725.0    1725.0
17  Neighborhood_ClearCr   1684.0    1684.0
23  Neighborhood_MeadowV   1650.0    1650.0
5            TotalBsmtSF  -1546.0    1546.0
39       BldgType_2fmCon   1477.0    1477.0
31    Neighborhood_SWISU  -1344.0    1344.0
49     HouseStyle_SFoyer   1342.0    1342.0
26  Neighborhood_NPkVill   1212.0    1212.0
22   Neighborhood_IDOTRR  -1002.0    1002.0
40       BldgType_Duplex  -1002.0    1002.0
43     HouseStyle_1.5Fin   -969.0     969.0
50       HouseStyle_SLvl    486.0     486.0
36   Neighborhood_Timber    322.0     322.0
16  Neighborhood_BrkSide    297.0     297.0
14  Neighborhood_Blueste    219.0     219.0
13  Neighborhood_Blmngtn     99.0      99.0
44     HouseStyle_1.5Unf    -54.0      54.0
46     HouseStyle_2.5Fin     53.0      53.0