In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

In [2]:
# SUPERVISED DATA  ## REGRESSION VARIABLE = Sale Price 
# SalePrice - the property's sale price in dollars. Target - variable to predict.

In [3]:
train_df = pd.read_csv(Path('resources/train.csv'))

In [4]:
train_df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
train_df.shape

(1460, 81)

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
print(train_df.BedroomAbvGr)

0       3
1       3
2       3
3       3
4       4
       ..
1455    3
1456    3
1457    4
1458    2
1459    3
Name: BedroomAbvGr, Length: 1460, dtype: int64

In [8]:
#DROP COLUMNS WITH LESS THAN 70% OF INFORMATION 
#Alley          107 non-null    object  
#FireplaceQu    729 non-null    object 
# PoolQC         3 non-null      object 
# Fence          290 non-null    object 
# MiscFeature    51 non-null     object 

train_df1 = train_df.drop(['Id','Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis='columns')
train_df1.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [9]:
train_df1.shape

(1460, 75)

In [10]:
# Delete rows with null values
train_df1 = train_df1.dropna()
train_df1.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000

In [11]:
train_df1.shape

(1094, 75)

In [12]:
# KEEP THE FOLOWING COLUMNS 

# MSZoning: Identifies the general zoning classification of the sale.
# LotArea: Lot size in square feet
# Utilities: Type of utilities available
# Neighborhood: Physical locations within Ames city limits
# BldgType: Type of dwelling
# HouseStyle: Style of dwelling
# OverallQual: Rates the overall material and finish of the house
# YearBuilt: Original construction date
# YearRemodAdd: Remodel date (same as construction date if no remodeling or additions)
# RoofMatl: Roof material
# Exterior1st: Exterior covering on house
# ExterQual: Evaluates the quality of the material on the exterior
# Foundation: Type of foundation
# BsmtQual: Evaluates the height of the basement
# BsmtFinType1: Rating of basement finished area
# BsmtFinSF1: Type 1 finished square feet
# BsmtFullBath: Basement full bathrooms
# BsmtHalfBath: Basement half bathrooms
# Heating: Type of heating
# HeatingQC: Heating quality and condition
# CentralAir: Central air conditioning
# Electrical: Electrical system
# 1stFlrSF: First Floor square feet
# 2ndFlrSF: Second floor square feet
# LowQualFinSF: Low quality finished square feet (all floors)
# KitchenQual: Kitchen quality
# Functional: Home functionality (Assume typical unless deductions are warranted)
# Fireplaces: Number of fireplaces
# GarageType: Garage location
# GarageFinish: Interior finish of the garage
# GarageCars: Size of garage in car capacity
# GarageQual: Garage quality
# PavedDrive: Paved driveway
#WoodDeckSF: Wood deck area in square feet
# OpenPorchSF: Open porch area in square feet
# EnclosedPorch: Enclosed porch area in square feet
# 3SsnPorch: Three season porch area in square feet
# ScreenPorch: Screen porch area in square feet
# PoolArea: Pool area in square feet
### MiscFeature: Miscellaneous feature not covered in other categories
# MiscVal: $Value of miscellaneous feature
# MoSold: Month Sold (MM)
# YrSold: Year Sold (YYYY)
# SaleType: Type of sale
# SaleCondition: Condition of sale

In [13]:
train_df2 = train_df1[["SalePrice", "MSZoning", "LotArea", "Utilities", "Neighborhood", "BldgType", "HouseStyle", "OverallQual", "YearBuilt", "YearRemodAdd", "RoofMatl", "Exterior1st", "ExterQual", "Foundation" , "BsmtQual", "BsmtFinType1", "BsmtFinSF1", "BsmtFullBath", "BsmtHalfBath", "Heating", "HeatingQC",  "CentralAir", "Electrical", "1stFlrSF", "2ndFlrSF", "LowQualFinSF", "KitchenQual", "Functional","Fireplaces", "GarageType", "GarageFinish", "GarageCars", "GarageQual", "PavedDrive", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch", "PoolArea", "MiscVal", "MoSold", "YrSold","SaleType", "SaleCondition"]]
train_df2.head()

,SalePrice,MSZoning,LotArea,Utilities,Neighborhood,BldgType,HouseStyle,OverallQual,YearBuilt,YearRemodAdd,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,208500,RL,8450,AllPub,CollgCr,1Fam,2Story,7,2003,2003,...,61,0,0,0,0,0,2,2008,WD,Normal
1,181500,RL,9600,AllPub,Veenker,1Fam,1Story,6,1976,1976,...,0,0,0,0,0,0,5,2007,WD,Normal
2,223500,RL,11250,AllPub,CollgCr,1Fam,2Story,7,2001,2002,...,42,0,0,0,0,0,9,2008,WD,Normal
3,140000,RL,9550,AllPub,Crawfor,1Fam,2Story,7,1915,1970,...,35,272,0,0,0,0,2,2006,WD,Abnorml
4,250000,RL,14260,AllPub,NoRidge,1Fam,2Story,8,2000,2000,...,84,0,0,0,0,0,12,2008,WD,Normal

In [14]:
# DATA DOES NOT HAVE DUPLICTES VALUES
print(train_df2.duplicated().sum())

0

### 1st CLEAN DATA 45 COLUMNS

In [17]:
train_df2.to_csv('resources/house_clean_data.csv')

In [18]:
train_df3 = train_df1[["SalePrice", "LotArea", "BedroomAbvGr", "FullBath", "HalfBath", "Neighborhood", "HouseStyle", "OverallQual", "YearBuilt" ]]
train_df3.head()

,SalePrice,LotArea,BedroomAbvGr,FullBath,HalfBath,Neighborhood,HouseStyle,OverallQual,YearBuilt
0,208500,8450,3,2,1,CollgCr,2Story,7,2003
1,181500,9600,3,2,0,Veenker,1Story,6,1976
2,223500,11250,3,2,1,CollgCr,2Story,7,2001
3,140000,9550,3,1,0,Crawfor,2Story,7,1915
4,250000,14260,4,2,1,NoRidge,2Story,8,2000

### 2ND CLEAN DATA 45 COLUMNS

In [19]:
train_df3.to_csv('resources/house_clean_data_2.csv', index=False)